version: '3.8'

services:
  forum:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - forum_data:/app/data
    restart: unless-stopped
    environment:
      - TZ=UTC

volumes:
  forum_data:
    driver: local 